export const fakeRecipes = [
    {
    id: 1, 
    name: 'Black Bean and Corn Quesadillas',
    image: '../assets/black-bean-and-corn-quesadillas.jpg', 
    type: 'mexican', 
    meal:['lunch', 'dinner'], 
    rating: 4.7, 
    numberOfReviews:1947,
    cookingTime: '40mins', 
    difficulty: 'moderate', 
    numberOfServings:8, 
    ingredients: ['2 teaspoons olive oil', '3 tablespoons finely chopped onion', '1 (15.5 ounce) can black beans, drained and rinsed', '1 (10 ounce) can whole kernel corn, drained', '¼ cup salsa', '1 tablespoon brown sugar', '¼ teaspoon red pepper flakes', '2 tablespoons butter', '8 (8 inch) flour tortillas', '1 ½ cups shredded Monterey Jack cheese' ], 
    directions: ['Heat olive oil in a large saucepan over medium heat. Cook and stir onion in hot oil until softened, about 2 minutes. Stir in beans and corn, then add salsa, brown sugar, and red pepper flakes; mix well. Cook until heated through, about 3 minutes. Remove from heat.', 'Melt about 1 ½ teaspoons butter in a large skillet over medium heat. Place a tortilla in the skillet. Sprinkle with ¼ of the Monterey Jack cheese, then top with ¼ of the bean mixture. Place another tortilla on top; cook until the bottom is golden, then carefully flip and cook until the other side is golden. Repeat with remaining tortillas and filling.']
    }, 
    {
    id: 2, 
    name: 'Beef Samosas',
    image: '../assets/samosas.jpg', 
    type: 'indian',
    meal:['breakfast'], 
    rating: 4.5, 
    numberOfReviews:244,
    cookingTime: '60mins', 
    difficulty: 'hard',
    numberOfServings:18, 
    ingredients: ['2 large potatoes, peeled', '1 cup frozen peas, thawed', '2 tablespoons vegetable oil', '½ teaspoon cumin seeds', '1 bay leaf, crushed', '1 pound ground beef', '2 large onions, finely chopped', '4 cloves garlic, crushed', '1 tablespoon minced fresh ginger root', '1 ½ teaspoons salt', '1 teaspoon ground cumin', '1 quart oil for deep frying', '2 tablespoons chopped fresh cilantro', '1 (16 ounce) package phyllo dough'], 
    directions: ['Bring a medium saucepan of lightly salted water to a boil. Stir in potatoes and peas; cook until potatoes are tender but still firm, about 15 minutes. Drain, mash together, and set aside.', 'Meanwhile, heat 2 tablespoons oil in a large saucepan over medium-high heat. Add cumin seeds and bay leaf; stir until fragrant and seeds are browned. Add ground beef and onions; cook until beef is browned and crumbly and onions are soft, about 5 to 7 minutes.', 'Stir in garlic and ginger. Season with salt, cumin, coriander, turmeric, chili powder, cinnamon, cardamom, and black pepper. Stir in the mashed potato mixture. Remove from heat and chill in the refrigerator for 1 hour, or until cool.', 'Heat 1 quart of oil in a deep saucepan over medium heat.', 'Mix cilantro and green chile peppers into potato and beef mixture. Place approximately 1 tablespoon of the mixture onto each phyllo sheet. Fold sheets into triangles, pressing edges together with moistened fingers.', 'Lower samosas carefully into the hot oil in batches. Fry until golden brown, about 3 minutes. Transfer to a paper towel-lined plate to drain. Repeat with remaining samosas. Serve warm.']
    },
    {
    id: 3, 
    name: 'Chef John`s Mulligatawny Soup',
    image: '../assets/Chef-Johns-Soup.jpg', 
    type: 'indian', 	
    meal:['lunch', 'dinner'], 
    rating: 4.9 , 
    numberOfReviews: 19,
    cookingTime: '1hr 40mins', 
    difficulty: 'hard', 
    numberOfServings:6, 
    ingredients: ['1 tablespoon unsalted butter', '1 tablespoon vegetable oil', '1 ¼ cups boneless, skinless chicken thighs', '1 teaspoon kosher salt, or more to taste', '1 tablespoon curry powder', '1 teaspoon garam masala', '½ teaspoon ground cumin', '4 cloves garlic, minced', '1 tablespoon finely grated fresh ginger','1 large yellow onion, diced', '2 carrots, diced', '2 stalks celery, diced', '1 tablespoon tomato paste', '1 cup cubed Yukon Gold potatoes', '½ cup seeded and diced tomato', '2 small Granny Smith apples - peeled, cored, and diced', '½ cup dry red lentils', '1 bay leaf', '1 teaspoon tamarind paste', '6 cups chicken broth', '½ cup plain Greek yogurt, or to taste','¼ cup chopped fresh cilantro, or to taste','¼ cup sliced green onion, or to taste','1 pinch red pepper flakes, or to taste'], 
    directions: ['Melt butter and oil in a soup pot over medium-high heat. Add chicken thighs and season with salt; let brown for 4 to 5 minutes. Flip and brown on opposite side, 4 to 5 minutes more.', 'While chicken browns, combine curry powder, garam masala, cumin, black pepper, ground mustard, coriander, and cayenne in a small bowl.', 'Remove browned chicken from the pot and transfer to a plate to cool enough to handle; roughly chop or shred.', 'While chicken cools, reduce heat to medium and add spice blend to pot; cook and stir until fragrant, about 30 seconds. Add garlic and ginger; cook and stir until fragrant, about 1 minute. Add onions, carrots, and celery. Season with salt and cook, stirring, until onions turn translucent, 3 to 4 minutes.', 'Stir in tomato paste and continue to cook for 3 minutes more.', 'Stir in potatoes, tomatoes, and apples. Add red lentils, bay leaf, and tamarind paste.', 'Pour in chicken broth, stir, and raise heat to high; add coconut cream. Bring to a simmer. Stir and reduce heat to medium-low. Let simmer, stirring occasionally, for about 30 minutes.', 'Stir chopped chicken and any accumulated juices into the soup. Continue to let simmer, stirring occasionally, until vegetables are fully cooked, lentils are tender, and soup has thickened, 20 to 30 minutes more. Taste and adjust as needed.', 'Serve in warm bowls topped with Greek yogurt, cilantro, and scallions. Sprinkle with red chili flakes.']
    },
    {
    id: 4, 
    name: 'Chickpea Tikka Masala',
    image: '../assets/chickpea-tikka-masala.jpg', 
    type: 'indian', 	
    meal:['lunch', 'dinner'], 
    rating: 5, 
    numberOfReviews:875,
    cookingTime: '35min', 
    difficulty: 'moderate', 
    numberOfServings:4, 
    ingredients: ['1 tablespoon olive oil', '1 medium onion, thinly sliced', '2 carrots, thinly sliced', '1 teaspoon garam masala', '1/4 teaspoon ground cumin', '1/8 teaspoon freshly ground black pepper', '1 tablespoon tomato paste', '1 1/2 teaspoons ginger paste', '1/2 teaspoon garlic paste', '1/2 medium fresh jalapeño chile pepper, finely chopped', '2 (15-ounce) cans chickpeas, rinsed and drained', '1 (8 ounce) can tomato sauce', '1/4 teaspoon sugar', '1/4 teaspoon salt', '1/8 teaspoon cayenne pepper (optional)', '3/4 cup water, or as needed', '1/4 cup half and half', '1/4 cup snipped fresh cilantro', '4 cups hot cooked basmati rice'], 
    directions: ['Heat oil in a large skillet over medium-high. Add onion and carrots and cook until tender, 5 to 6 minutes.', 'Stir in garam masala, cumin, and black pepper; cook and stir until mixture is fragrant, about 30 seconds.', 'Add tomato paste, ginger paste, garlic paste, and jalapeño pepper; cook and stir for 2 minutes.', 'Stir in chickpeas, tomato sauce, sugar, salt, and cayenne pepper. Cook over medium-high heat until mixture is hot. Reduce heat to low. Cover and simmer for 10 minutes.', 'Stir in 3/4 cup water and half-and-half. Continue cooking on low until heated through, about 1 minute. For a saucier mixture, add more water if desired. Remove from heat; cover and keep warm.', 'Top with cilantro and serve with hot cooked basmati rice and/or naan.']
    },
    {
    id: 5, 
    name: 'Lazy Wonton Soup',
    image: '../assets/Lazy-Wonton-Soup.jpg', 
    type: 'chinese', 	
    meal:['breakfast', 'lunch'], 
    rating: 4.7, 
    numberOfReviews:72,
    cookingTime: '40mins', 
    difficulty: 'easy', 
    numberOfServings:6, 
    ingredients: ['2 quarts chicken stock or broth', '1 bunch green onions, divided', '1 garlic clove, thinly sliced', '1 (3-inch) piece fresh ginger, peeled, or 2 teaspoons ground ginger', '2 tablespoons soy sauce, plus more to taste', '1 1/2 teaspoons rice vinegar', '1 tablespoon brown sugar', '1 teaspoon kosher salt, divided', '1 pound ground pork', '2 teaspoons toasted sesame oil', '2 teaspoons cornstarch', '3 heads baby bok choy, roughly chopped', '20 wonton wrappers, cut into quarters', 'Sriracha hot sauce or chili crunch (optional)'], 
    directions: ['Place chicken stock in a large saucepan or Dutch oven over medium-high heat. Cut white parts of green onions into 1-inch pieces and add to broth. Add garlic clove. Thinly slice 1 inch ginger (or 1 teaspoon ground)  and add to stock. Add 1 tablespoon soy sauce, vinegar, brown sugar and 1/2 teaspoon salt. Bring mixture to a boil, stirring occasionally.', 'Place pork in a bowl. Finely slice remaining green parts of green onions. Set aside 3 tablespoons for garnish. Add remaining onions to the bowl; grate in remaining 2-inch piece of ginger. Add remaining soy sauce, remaining salt, sesame oil, and cornstarch to the bowl; mix until well combined.', 'Form mixture into 1-inch balls and add to broth. Alternatively, use a small spoon to drop heaping teaspoons full of meat into broth. Reduce heat to a simmer; cook 5 minutes. Add wonton wrappers, bok choy, and additional soy sauce to taste. Cook 8 minutes, stirring occasionally. ', 'Serve with reserved green onions and hot sauce or chili crisp if desired.']
    },
    {
    id: 6, 
    name: 'Blackened Shrimp Tacos with Pineapple',
    image: '../assets/Blackened-Shrimp-and-Pineapple-Tacos.jpg', 
    type: 'mexican', 	
    meal:['lunch', 'dinner'], 
    rating: 4.3, 
    numberOfReviews:72,
    cookingTime: '30mins', 
    difficulty: 'easy', 
    numberOfServings:3, 
    ingredients: ['2 tablespoons smoked paprika', '1 tablespoon onion powder', '1 tablespoon dried oregano', '1 teaspoon cayenne pepper', '1 teaspoon garlic salt', '1 teaspoon freshly ground black pepper', '1/2 fresh pineapple, peeled and cored', '1/4 cup chopped red onions', '1/4 cup chopped cilantro', '1 lime, juiced', '1/8 teaspoon salt', '1 pound large shrimp, peeled and deveined', '2 tablespoons melted butter', '6 (6 inch) flour tortillas'], 
    directions: ['Preheat an outdoor grill for medium-high heat; lightly oil the grate. Combine paprika, onion powder, oregano, cayenne pepper, garlic salt, and black pepper in a small bowl; set aside.', 'Cut the pineapple lengthwise into wedges. Grill pineapple wedges for 4 to 5 minutes on each side. Chop pineapple and combine in a bowl with red onions, cilantro, fresh lime juice, and salt.', 'Thread shrimp onto skewers; brush with melted butter, and coat with seasoning mix. Grill shrimp until they are bright pink on the outside and the meat is opaque, about 3 minutes per side.', 'Place tortillas on the hot grill and heat until lightly grilled, 20 to 30 seconds per side.', 'Place shrimp on each tortilla and top with pineapple mixture.']
    },
    {
    id: 7, 
    name: 'Sesame Chicken with Broccoli',
    image: '../assets/Stir-Fried-Sesame-Chicken-with-Broccoli.jpg',
    type: 'chinese', 	
    meal:['dinner'], 
    rating: 4.2, 
    numberOfReviews:52,
    cookingTime: '45mins', 
    difficulty: 'moderate', 
    numberOfServings:4, 
    ingredients: ['1 1/2 pounds boneless skinless chicken breast, cut into 1-inch pieces','2 teaspoons cornstarch', '1 teaspoon salt, or to taste', '1/4 teaspoon white pepper, or to taste', '2 teaspoons minced fresh garlic', '2 teaspoons minced fresh ginger', '1/4 cup plus 1 teaspoon cooking oil of choice, divided', '1/3 cup soy sauce', '1/3 cup hoisin sauce' , '1/3 cup rice vinegar', '1 teaspoon sambal oelek, or to taste', '2 tablespoons sesame oil', '1/2 cup carrots, cut into matchsticks', '1/2 cup sliced shallots', '4 cups fresh broccoli florets', '1 tablespoon cornstarch', '1 tablespoon soy sauce', '1 tablespoon sesame seeds, or to taste'], 
    directions: ['Place chicken pieces in a bowl. Sprinkle with cornstarch, salt, and white pepper. Toss chicken to coat evenly and set aside.', 'Heat 1 teaspoon cooking oil in a small nonstick skillet over medium heat. Add garlic and ginger and cook, stirring, until fragrant, about 1 minute.', 'Stir in soy sauce, hoisin sauce, rice vinegar, sambal oelek, and sesame oil. Bring to a boil and cook, stirring, about 1 minute. Remove from heat and set aside.', 'Heat 2 tablespoons oil over medium-high heat in a large nonstick skillet or wok until very hot. Add chicken pieces carefully to the hot oil. Cook, stirring, until chicken pieces are lightly browned on all sides, 8 to 10 minutes total. The chicken pieces will cause spattering, so be sure to use a long-handled spoon or other utensil to move the chicken around.', 'Using a slotted spoon, remove chicken from the skillet and add the remaining 2 tablespoons cooking oil. Add carrots, shallots, and broccoli, and stir quickly and continually, 3 to 4 minutes.', 'Stir in prepared sauce, and cook until the vegetables are as tender as you like, 2 to 3 minutes.', 'Place cornstarch in a small bowl and stir in 1 tablespoon soy sauce. Keep stirring until there are no lumps. Add cornstarch slurry to the skillet and rapidly stir until well combined. Return chicken pieces and cook, stirring often, until heated through, 2 to 3 minutes.', 'Remove from heat, sprinkle with sesame seeds, and serve hot.']
    },
    {
    id: 8, 
    name: 'Mexican Street Corn Deviled Eggs',
    image: '../assets/Mexican-Street-Corn-Deviled-Eggs.jpg', 
    type: 'mexican', 	
    meal:['breakfast'], 
    rating: 4.5, 
    numberOfReviews:534,
    cookingTime: '25mins', 
    difficulty: 'easy', 
    numberOfServings:6, 
    ingredients: ['6 large eggs', '3 ounces prepared Mexican street corn dip', '2 tablespoons mayonnaise', '2 teaspoons freshly squeezed lime juice, or to taste', '1 tablespoon crumbled cotija cheese, divided', '1 tablespoon slivered red onion', '2 teaspoons chopped cilantro', '1 teaspoon chili-lime seasoning, such as Tajin® Clásico Seasoning'], 
    directions: ['Place eggs in a saucepan and cover with water. Bring to a boil, remove from heat, and let eggs stand in hot water for 15 minutes. Remove eggs from hot water, cool under cold running water, and peel. Cut eggs in half lengthwise.', 'Remove yolks to a small mixing bowl; mash with a fork. Add in Mexican street corn dip, mayonnaise, and lime juice. Stir together with a fork until fairly smooth; stir in 2 teaspoons of cotija cheese.', 'Fit a piping bag with a coupler and a tip with a fairly large opening. Drop piping bag into a tall glass and fold edges down around the glass. Spoon egg yolk filling into the bag. Gather edges and twist together. Pipe filling into egg whites. Alternately, spoon filling into a resealable plastic bag, press to remove excess air, and reseal. Cut one corner of bag off, and pipe filling into egg whites. Or, simply spoon filling into egg whites.', 'Sprinkle remaining cotija cheese over eggs; scatter on onion slivers and cilantro. Sprinkle with Tajin® seasoning and serve.']
    },
    {
    id: 9, 
    name: 'Pork Dumplings',
    image: '../assets/pork-dumplings.jpg', 
    type: 'chinese', 	
    meal:['breakfast', 'lunch', 'dinner'], 
    rating: 4.6, 
    numberOfReviews:382,
    cookingTime: '1hr', 
    difficulty: 'hard', 
    numberOfServings:10, 
    ingredients: ['100 (3.5 inch square) wonton wrappers', '1 ¾ pounds ground pork', '1 tablespoon minced fresh ginger root', '4 cloves garlic, minced', '2 tablespoons thinly sliced green onion', '4 tablespoons soy sauce', '3 tablespoons sesame oil', '1 egg, beaten', '5 cups finely shredded Chinese cabbage'], 
    directions: ['In a large bowl, combine the pork, ginger, garlic, green onion, soy sauce, sesame oil, egg and cabbage. Stir until well mixed.', 'Place 1 heaping teaspoon of pork filling onto each wonton skin. Moisten edges with water and fold edges over to form a triangle shape. Roll edges slightly to seal in filling. Set dumplings aside on a lightly floured surface until ready to cook.', 'Arrange dumplings in a covered bamboo or metal steamer so they don`t touch to prevent them from sticking together; steam for 15 minutes, or until pork is cooked through.', 'Serve hot and enjoy!']
    }
]; 